import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {


  const { data, isLoading } = api.post.getVehicles.useQuery()

  if (isLoading) return <div>Loading...</div>

  if (!data) return (
    <h1>No team data found, add a new team <Link href="/add-team">HERE</Link></h1>
  )


  return (
    <>
      <Head>
        <title>Basstrack</title>
        <meta name="description" content="Official website of bass fishing" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="bg-contain bg-center w-full md:max-w-2xl bg-[url('https://scontent-jnb1-1.xx.fbcdn.net/v/t39.30808-6/260277972_10227320945231659_2177364538079183029_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=1ac024&_nc_ohc=BNUj0U7h4X0AX9ag8BH&_nc_ht=scontent-jnb1-1.xx&oh=00_AfDC04u-kGWkfzpbF3M2J_AV6brZETHXZaWgnR4ow5Zj7A&oe=65175085')]">
          <div className="flex pl-1 pt-1 pb-1">
          </div>
          <table className="w-full mt-5">
            <tr>
              <td className="font-bold text-center border-b border-x bg-blue-500">Stock Number</td>
              <td className="font-bold text-center border-b border-x bg-blue-500">Make</td>
              <td className="font-bold text-center border-b border-x bg-blue-500">Model</td>
            </tr>
            {data.map((e) => (
              <tr key={e.stockNumber} className="bg-black bg-opacity-70 text-slate-300 font-bold ml-6 border-b">
                <td className="text-center border-x"><Link href={e.stockNumber}>{e.stockNumber}</Link></td>
                <td className="text-center border-x">{e.make}</td>
                <td className="text-center border-x">{e.model}</td>
              </tr>
            ))}
          </table>
        </div>
      </main>
    </>
  );
}

//   return (
//     <div style={{ padding: '5%', width: '100vw', height: '100vh' }}>
//       <table style={{ width: '100%', height: '100%', borderCollapse: 'collapse' }}>
//         <thead>
//           <tr>
//             {/* Define your table headers based on your data structure */}
//             <th>Column 1</th>
//             <th>Column 2</th>
//             {/* Add more headers if needed */}
//           </tr>
//         </thead>
//         <tbody>
//           {vehicles.data ? vehicles.data.map((e) => (
//             <tr key={e.vId}>
//               {/* Populate table cells with data */}
//               <td>{e.stockNumber}</td>
//               <td>{ e.make}</td>
//               <td>{ e.model}</td>
//               {/* Add more cells if needed */}
//             </tr>
//           )) : "Loading Vehicles"}
//         </tbody>
//       </table>
//     </div>
//   );
// };

// return (
//   <>
//     <Head>
//       <title>PMG Trade Centre</title>
//       <meta name="Homepage" content="Generated by Kewan Seymour" />
//       <link rel="icon" href="https://produktamotorgroup.co.za/wp-content/uploads/2024/01/logo.png" />
//     </Head>
//     <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
//       <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//         <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
//           Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
//         </h1>
//         <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
//           <Link
//             className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//             href="https://create.t3.gg/en/usage/first-steps"
//             target="_blank"
//           >
//             <h3 className="text-2xl font-bold">First Steps →</h3>
//             <div className="text-lg">
//               Just the basics - Everything you need to know to set up your
//               database and authentication.
//             </div>
//           </Link>
//           <Link
//             className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//             href="https://create.t3.gg/en/introduction"
//             target="_blank"
//           >
//             <h3 className="text-2xl font-bold">Documentation →</h3>
//             <div className="text-lg">
//               Learn more about Create T3 App, the libraries it uses, and how
//               to deploy it.
//             </div>
//           </Link>
//         </div>
//         <p className="text-2xl text-white">
//           {vehicle.data ? vehicle.data.map(e => {
//             return <p>{e.model}</p>
//           }) : "Loading Stock Number"}
//         </p>
//       </div>
//     </main>
//   </>
// );